# Proxy Configuration
proxy:

  # All proxy options can also be set from CLI flags
  listen: "localhost:8081"
  target: "http://localhost:8080"

  # timeout: 30s
  # ssl_cert: certificate.pem
  # ssl_key: key.pem
  # debug: true

# Request Rules
rules:

  # `methods`, `paths` and `filters` field values are regex patterns. Include a
  # string or array of strings.
  - methods: POST
    paths: .*/chat/completions

    # Optionally normalize the request path.
    target_path: /v1/chat/completions

    # First matched operation wins. Each should contain one or more actions
    # (default, merge, delete) that execute in the order written. Operations
    # without filters match everything.
    operations:
      - filters:
          model: deepseek-?(v3|r1)
        merge:
          temperature: 0.6
          top_p: 0.95

      - filters:
          model: gemma-?3
        merge:
          temperature: 1
          top_k: 64
          top_p: 0.95
          min_p: 0

      - filters:
          model: glm-?4
        merge:
          temperature: 0.6
          top_p: 1

      - filters:
          model: gpt-oss
        merge:
          temperature: 1
          top_k: 0
          top_p: 1
          min_p: 0

      - filters:
          model: qwen-?3.*-coder
        merge:
          temperature: 0.7
          top_k: 20
          top_p: 0.8
          min_p: 0
          repeat_penalty: 1.05

      - filters:
          model: qwen-?3.*-instruct
        merge:
          temperature: 0.7
          top_k: 20
          top_p: 0.8
          min_p: 0

      - filters:
          model: qwen-?3.*-thinking
        merge:
          temperature: 0.6
          top_k: 20
          top_p: 0.95
          min_p: 0

      # Catch all
      - merge:
          temperature: 0.5

  - methods: POST
    paths: .*/infill
    operations:
      - merge:
          temperature: 0.7
          top_k: 20
          top_p: 0.8
          min_p: 0
          repeat_penalty: 1.05