# Proxy configuration
proxy:
  listen: "localhost:8081"
  target: "http://localhost:8080"

  # Optional
  timeout: 30s
  ssl_cert: certificate.pem
  ssl_key: key.pem

# Overrides
match:
  - methods:
      - POST
    endpoints:
      - /v1/chat/completions
      - /chat/completions
    overrides:
      - models: gemma3.*
        params:
          temperature: 1.0
          top_k: 64
          top_p: 0.95
          min_p: 0
      - models: qwen3-coder
        params:
          temperature: 0.7
          top_k: 20
          top_p: 0.8
          min_p: 0
          repeat_penalty: 1.05
      - match: qwen3-.*
        params:
          temperature: 0.6
          top_k: 20
          top_p: 0.95
          min_p: 0