# Proxy configuration
proxy:
  listen: "localhost:8081"
  target: "http://localhost:8080"

  # timeout: 30s
  # ssl_cert: certificate.pem
  # ssl_key: key.pem
  # debug: true

# Overrides
match:
  - methods:
      - POST
    endpoints:
      - /v1/chat/completions
      - /chat/completions

    # models: supports one or many regex patterns. First match is applied.
    overrides:
      - models: deepseek-?v3
        params:
          temperature: 0.6
          top_p: 0.95
      - models: deepseek-?r1
        params:
          temperature: 0.6
          top_p: 0.95
      - models: gemma-?3
        params:
          temperature: 1
          top_k: 64
          top_p: 0.95
          min_p: 0
      - models: glm-?4
        params:
          temperature: 0.6
          top_p: 1
      - models: gpt-oss
        params:
          temperature: 1
          top_k: 0
          top_p: 1
          min_p: 0
      - models: qwen-?3.*-coder
        params:
          temperature: 0.7
          top_k: 20
          top_p: 0.8
          min_p: 0
          repeat_penalty: 1.05
      - models: qwen-?3.*-instruct
        params:
          temperature: 0.7
          top_k: 20
          top_p: 0.8
          min_p: 0
      - models: qwen-?3.*-thinking
        params:
          temperature: 0.6
          top_k: 20
          top_p: 0.95
          min_p: 0